kind: pipeline
type: docker
name: test-and-build
platform:
  os: linux
  arch: arm64

steps:
  - name: install-dependencies
    image: ruby:3.4
    environment:
      REDIS_URL: ${REDIS_URL}
      MONGODB_URI: ${MONGO_URL_TEST}
    commands:
      - apt-get update -qq && apt-get install -y nodejs npm
      - gem install bundler
      - rm -rf vendor/bundle
      - bundle install

  - name: setup-database
    image: ruby:3.4
    environment:
      RAILS_ENV: test
      REDIS_URL: ${REDIS_URL}
      MONGODB_URI: ${MONGO_URL_TEST}
    commands:
      - bundle exec rake db:create
      - bundle exec rake db:schema:load

  - name: run-tests
    image: ruby:3.4
    environment:
      RAILS_ENV: test
      REDIS_URL: ${REDIS_URL}
      MONGODB_URI: ${MONGODB_URI}
    commands:
      - bundle exec sidekiq -q default -d
      - bundle exec rails test

services:
  - name: redis
    image: redis:7

  - name: mongo
    image: mongo:6
