kind: pipeline
type: docker
name: test-and-build
platform:
  os: linux
  arch: arm64

steps:
  - name: install-dependencies
    image: ruby:3.4
    environment:
      REDIS_URL: ${REDIS_URL}
      MONGODB_URI: ${MONGO_URL_TEST}
    commands:
      - apt-get update -qq && apt-get install -y nodejs npm
      - gem install bundler:2.7.2
      - rm -rf vendor/bundle
      - bundle lock --add-platform x86_64-linux
      - bundle _2.7.2_ config set --local path 'vendor/bundle'
      - bundle _2.7.2_ install --jobs 4 --retry 3

  - name: setup-database
    image: ruby:3.4
    environment:
      RAILS_ENV: test
      REDIS_URL: ${REDIS_URL}
      MONGODB_URI: ${MONGO_URL_TEST}
    commands:
      - gem install bundler:2.7.2
      - bundle _2.7.2_ config set --local path 'vendor/bundle'
      - bundle _2.7.2_ exec rake db:create
      - bundle _2.7.2_ exec rake db:schema:load

  - name: run-tests
    image: ruby:3.4
    environment:
      RAILS_ENV: test
      REDIS_URL: ${REDIS_URL}
      MONGODB_URI: ${MONGO_URL_TEST}
    commands:
      - gem install bundler:2.7.2
      - bundle _2.7.2_ config set --local path 'vendor/bundle'
      - bundle _2.7.2_ exec sidekiq -q default -d
      - bundle _2.7.2_ exec rails test

services:
  - name: redis
    image: redis:7

  - name: mongo
    image: mongo:6