development:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: <%= ENV['MONGO_URL_TEST'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        server_selection_timeout: 5
